{% set org = "python-streamz" %}
{% set name = "streamz" %}
{% set version = "0.6.5" %}
{% set sha256 = "d9ae5f4665c2a261950980c94dfa7f767507d2e33950651936c74b587cacaf22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - zict
    - tornado
    - toolz
    - setuptools
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - streamz
    - streamz.core

about:
  home: https://github.com/python-streamz/streamz/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Manage streaming data, optionally with Dask and Pandas

  description: |
    Manage streaming data, optionally with Dask and Pandas
  doc_url: https://streamz.readthedocs.io/en/latest/
  dev_url: https://github.com/python-streamz/streamz/

extra:
  recipe-maintainers:
    - CJ-Wright
    - mrocklin
    - jrmlhermitte
    - mariusvniekerk
    - martindurant
